apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <<CLAW_PVC>>
  namespace: <<NAMESPACE>>
spec:
  storageClassName: <<NFS_SC_NAME>>
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: <<CLAW_STORAGE_SIZE>>
  
