apiVersion: v1
kind: ServiceAccount
metadata:
  name: <<NFS_SC_DNAME>>

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: <<NFS_SC_DNAME>>-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: run-<<NFS_SC_DNAME>>
subjects:
  - kind: ServiceAccount
    name: <<NFS_SC_DNAME>>
    namespace: default
roleRef:
  kind: ClusterRole
  name: <<NFS_SC_DNAME>>-runner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-locking-<<NFS_SC_DNAME>>
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-locking-<<NFS_SC_DNAME>>
subjects:
  - kind: ServiceAccount
    name: <<NFS_SC_DNAME>>
roleRef:
  kind: Role
  name: leader-locking-<<NFS_SC_DNAME>>
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <<NFS_SC_DNAME>>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <<NFS_SC_DNAME>>
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: <<NFS_SC_DNAME>>
    spec:
      serviceAccount: <<NFS_SC_DNAME>>
      containers:
        - name: <<NFS_SC_DNAME>>
          image: <<NFS_SC_IMAGE>>
          volumeMounts:
            - name: nfs-volume
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: <<NFS_SC_DNAME>>
            - name: NFS_SERVER
              value: <<NFS_SERVER_ADDR>>
            - name: NFS_PATH
              value: <<NFS_SHARE_PATH>>
      volumes:
        - name: nfs-volume
          nfs:
            server: <<NFS_SERVER_ADDR>>
            path: <<NFS_SHARE_PATH>>

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: <<NFS_SC_NAME>>
provisioner: <<NFS_SC_DNAME>>
parameters:
  archiveOnDelete: "true"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4
  - soft        # 改成 soft！防止节点卡死
  - timeo=600   # 超时时间：60秒
  - retrans=2   # 重试2次
  - noatime
