apiVersion: apps/v1
kind: Deployment
metadata:
  name: <<NFS_NAME>>
  namespace: default
  labels:
    app: <<NFS_NAME>>
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: <<NFS_NAME>>
  template:
    metadata:
      labels:
        app: <<NFS_NAME>>
    spec:
      # 固定调度到本master节点（运行部署工具的节点）
      nodeName: <<CURRENT_NODE_NAME>>
      hostNetwork: true
      containers:
        - name: <<NFS_NAME>>
          image: <<NFS_IMAGE>>
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: NFS_DISABLE_VERSION_3
              value: "1"
            - name: NFS_EXPORT_0
              value: "/exports *(rw,sync,no_subtree_check,no_root_squash,fsid=0,insecure)"
          ports:
            - containerPort: 2049
              name: nfs
            - containerPort: 111
              name: rpcbind
          volumeMounts:
            - name: nfs-storage
              mountPath: /exports
      volumes:
        - name: nfs-storage
          hostPath:
            path: <<NFS_HOST_PATH>>
            type: DirectoryOrCreate
