"""Wire constants and capability-neutral error codes for Reverse RPC V1."""

REVERSE_RPC_VERSION = 1

REVERSE_RPC_REQUEST_KIND = "reverse_rpc.request"
REVERSE_RPC_CANCEL_KIND = "reverse_rpc.cancel"
REVERSE_RPC_RESPONSE_METHOD = "reverse_rpc.response"

ERROR_INVALID_REQUEST = "INVALID_REQUEST"
ERROR_UNSUPPORTED_VERSION = "UNSUPPORTED_VERSION"
ERROR_INVALID_RESPONSE = "INVALID_RESPONSE"
ERROR_METHOD_NOT_FOUND = "METHOD_NOT_FOUND"
ERROR_ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
ERROR_CHANNEL_NOT_READY = "CHANNEL_NOT_READY"
ERROR_TIMEOUT = "TIMEOUT"
ERROR_CANCELLED = "CANCELLED"
ERROR_TRANSPORT_DISCONNECTED = "TRANSPORT_DISCONNECTED"
ERROR_INTERNAL = "INTERNAL_ERROR"
ERROR_OVERLOADED = "REVERSE_RPC_OVERLOADED"
ERROR_RESULT_TOO_LARGE = "RESULT_TOO_LARGE"
