# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.

"""Memory system for JiuWenClaw."""

from .types import (
    MemorySearchResult,
    MemoryProviderStatus,
    MemorySyncProgressUpdate,
    MemoryFileEntry,
    MemoryChunk,
    SessionFileEntry,
    MemorySource,
    FileEntry,
    FtsStatus,
    VectorStatus,
)
from .manager import MemoryIndexManager, get_memory_manager, clear_memory_manager_cache
from .config import (
    MemorySettings,
    create_memory_settings,
    is_memory_enabled,
    get_embed_config,
    DEFAULT_WORKSPACE_DIR,
)
from .embeddings import EmbeddingProvider, create_embedding_provider
from .summarizer import (
    LLMClient,
    MemoryCompactor,
    MemorySummarizer,
    compact_memory,
    summarize_session,
    format_messages_for_summary,
)
from .compaction import (
    MessageMark,
    Message,
    TokenCounter,
    MessageStore,
    CompactionManager,
    MEMORY_COMPACT_THRESHOLD,
    MEMORY_COMPACT_KEEP_RECENT,
)
from .internal import estimate_tokens
from .internal import (
    ensure_dir,
    list_memory_files,
    build_file_entry,
    chunk_markdown,
    hash_text,
    parse_embedding,
    build_fts_query,
    bm25_rank_to_score,
    is_memory_path,
    normalize_extra_memory_paths,
)

__all__ = [
    "MemoryIndexManager",
    "MemorySettings",
    "get_memory_manager",
    "clear_memory_manager_cache",
    "EmbeddingProvider",
    "create_embedding_provider",
    "MemorySearchResult",
    "MemoryProviderStatus",
    "MemorySyncProgressUpdate",
    "MemoryFileEntry",
    "MemoryChunk",
    "SessionFileEntry",
    "MemorySource",
    "MemoryEmbeddingProbeResult",
    "SourceCount",
    "CacheStatus",
    "FtsStatus",
    "VectorStatus",
    "BatchStatus",
    "ensure_dir",
    "list_memory_files",
    "build_file_entry",
    "chunk_markdown",
    "hash_text",
    "parse_embedding",
    "build_fts_query",
    "bm25_rank_to_score",
    "is_memory_path",
    "normalize_extra_memory_paths",
    "create_memory_settings",
    "is_memory_enabled",
    "get_embed_config",
    "DEFAULT_WORKSPACE_DIR",
    "LLMClient",
    "MemoryCompactor",
    "MemorySummarizer",
    "compact_memory",
    "summarize_session",
    "format_messages_for_summary",
    "MessageMark",
    "Message",
    "TokenCounter",
    "MessageStore",
    "CompactionManager",
    "MEMORY_COMPACT_THRESHOLD",
    "MEMORY_COMPACT_KEEP_RECENT",
    "estimate_tokens",
]
