# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.

"""Memory system for JiuWenClaw."""

from .types import (
    MemorySearchResult,
    MemoryFileEntry,
    MemoryChunk,
    MemorySource,
    FileEntry,
)
from .manager import (
    MemoryIndexManager,
    get_memory_manager,
    clear_memory_manager_cache,
    invalidate_memory_manager_cache,
    invalidate_memory_wiki_manager_cache,
    build_index_cache_key,
)
from .cache_registry import (
    acquire_memory_cache_session,
    release_memory_cache_session,
    bind_memory_cache_fingerprint,
    reset_memory_cache_fingerprint,
    get_bound_memory_cache_fingerprint,
    get_memory_cache_ref_count,
    clear_memory_cache_registry,
    close_memory_cache_entry,
    release_all_memory_cache_sessions,
)
from .wiki_manager import MemoryWikiManager
from .config import (
    MemorySettings,
    WikiMemorySettings,
    create_memory_settings,
    create_wiki_memory_settings,
    default_workspace_dir,
    is_memory_enabled,
    get_memory_mode,
    get_embed_config,
)
from .embeddings import EmbeddingProvider, create_embedding_provider
from .external_memory_config import (
    get_external_memory_config,
    is_external_memory_enabled,
    build_openjiuwen_provider_config,
    external_memory_fingerprint,
    get_memory_engine,
    is_builtin_memory_allowed,
    is_external_memory_allowed,
)
from .external_memory_builder import build_external_memory_rail
from .internal import (
    estimate_tokens,
    ensure_dir,
    list_memory_files,
    list_daily_memory_files,
    build_file_entry,
    chunk_markdown,
    hash_text,
    build_fts_query,
    bm25_rank_to_score,
    is_memory_path,
    is_daily_memory_file,
    normalize_extra_memory_paths,
)

__all__ = [
    "MemoryIndexManager",
    "MemoryWikiManager",
    "MemorySettings",
    "WikiMemorySettings",
    "get_memory_manager",
    "clear_memory_manager_cache",
    "invalidate_memory_manager_cache",
    "invalidate_memory_wiki_manager_cache",
    "build_index_cache_key",
    "acquire_memory_cache_session",
    "release_memory_cache_session",
    "bind_memory_cache_fingerprint",
    "reset_memory_cache_fingerprint",
    "get_bound_memory_cache_fingerprint",
    "get_memory_cache_ref_count",
    "clear_memory_cache_registry",
    "close_memory_cache_entry",
    "release_all_memory_cache_sessions",
    "EmbeddingProvider",
    "create_embedding_provider",
    "MemorySearchResult",
    "MemoryFileEntry",
    "MemoryChunk",
    "MemorySource",
    "FileEntry",
    "ensure_dir",
    "list_memory_files",
    "build_file_entry",
    "chunk_markdown",
    "hash_text",
    "build_fts_query",
    "bm25_rank_to_score",
    "is_memory_path",
    "is_daily_memory_file",
    "list_daily_memory_files",
    "normalize_extra_memory_paths",
    "create_memory_settings",
    "create_wiki_memory_settings",
    "is_memory_enabled",
    "get_memory_mode",
    "get_embed_config",
    "default_workspace_dir",
    "estimate_tokens",
    "get_external_memory_config",
    "is_external_memory_enabled",
    "build_openjiuwen_provider_config",
    "build_external_memory_rail",
    "get_memory_engine",
    "is_builtin_memory_allowed",
    "is_external_memory_allowed",
    "external_memory_fingerprint",
]
