apiVersion: v1
kind: Secret
metadata:
  name: jiuwenclaw-secret-configmap
  namespace: jiuwenclaw
type: Opaque
data:
  GATEWAY_DB_PASSWORD: "PDxEQl9QQVNTV09SRD4+"
  MANAGER_DB_PASSWORD: "PDxEQl9QQVNTV09SRD4+"
  REDIS_PASSWORD: "PDxSRURJU19QQVNTV09SRD4+"
  JIUWENCLAW_MINIO_SECRET_KEY: "PDxPQlNfU0VDUkVUX0tFWT4+"
  API_KEY: "PDxBUElfS0VZPj4="
