apiVersion: v1
kind: Secret
metadata:
  name: <<SECRET_CM_NAME>>
  namespace: <<NAMESPACE>>
type: Opaque
stringData:
  # 这里放所有敏感密码，无需base64编码，apply时自动加密
  GATEWAY_DB_PASSWORD: "<<GATEWAY_DB_PASSWORD>>"
  MANAGER_DB_PASSWORD: "<<MANAGER_DB_PASSWORD>>"
  REDIS_PASSWORD: "<<REDIS_PASSWORD>>"
  JIUWENCLAW_MINIO_SECRET_KEY: "<<MINIO_ROOT_PASSWORD>>"
  API_KEY: "<<API_KEY>>"
