ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG AGENT_RUNTIME_REPOS
ARG AGENT_RUNTIME_BRANCH

RUN useradd --create-home --shell /bin/bash app

WORKDIR /app/jiuwenclaw
COPY . /app/jiuwenclaw/
RUN chown -R app:app /app/jiuwenclaw

RUN sed -i '/openjiuwen_runtime_foundation/d' pyproject.toml
RUN sed -i '/openjiuwen_runtime_foundation/d' packages/jiuwenclaw-ee/claw_manager/pyproject.toml
RUN sed -i '/openjiuwen_runtime_foundation/d' packages/jiuwenclaw-ee/identity_service/pyproject.toml
RUN sed -i '/openjiuwen_runtime_management/d' packages/jiuwenclaw-ee/gateway/extensions/runtime_management_extension/pyproject.toml

RUN pip install -e "./packages/jiuwenclaw-ee/identity_service" \
    git+${AGENT_RUNTIME_REPOS}@${AGENT_RUNTIME_BRANCH}#subdirectory=foundation \
    --no-cache-dir \
    -i https://pypi.tuna.tsinghua.edu.cn/simple

USER app
WORKDIR /app/jiuwenclaw
ENV PATH=$PATH:/home/app/.local/bin

EXPOSE 8770
CMD ["jiuwenclaw-identity"]
