ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG AGENT_RUNTIME_REPOS
ARG AGENT_RUNTIME_BRANCH

RUN apt-get update && apt-get install -y --no-install-recommends yq

WORKDIR /app/jiuwenclaw
COPY . /app/jiuwenclaw/

ENV PATH=$PATH:/home/app/.local/bin

RUN pip install -e ".[all]" \
    git+${AGENT_RUNTIME_REPOS}@${AGENT_RUNTIME_BRANCH}#subdirectory=foundation \
    git+${AGENT_RUNTIME_REPOS}@${AGENT_RUNTIME_BRANCH}#subdirectory=management \
    kubernetes==35.0.0 \
    kubernetes_asyncio==35.0.0 \
    "websockets>=12.0,<16" \
    pydantic-settings>=2.0 \
    python-dotenv>=1.0 \
    --no-cache-dir \
    -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN yq -y -i '.dependencies = {}' packages/jiuwenclaw-ee/gateway/extensions/runtime_management_extension/extension.yaml
RUN yq -y -i '.dependencies = {}' packages/jiuwenclaw-ee/gateway/extensions/manager_ws_client/extension.yaml

RUN mkdir -p /home/app/.jiuwenclaw && printf 'yes\nzh\n' | jiuwenclaw-init

EXPOSE 19000
CMD ["jiuwenclaw-gateway"]