FROM python:3.11.4-slim-bookworm

RUN useradd --create-home --shell /bin/bash app

WORKDIR /app/jiuwenclaw
COPY . /app/jiuwenclaw/
RUN chown -R app:app /app/jiuwenclaw

USER app
ENV PATH=$PATH:/home/app/.local/bin

RUN pip install -e ".[all]" --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN mkdir -p /home/app/.jiuwenclaw && printf 'yes\nzh\n' | jiuwenclaw-init

EXPOSE 19000
CMD ["jiuwenclaw-gateway"]
