"""openjiuwen TableDefinition 声明。"""

from .enterprise_models import (
    CONFIG_DEFAULT_TEMPLATE_MAPPING_TABLE_DEF,
    CONFIG_EFFECTIVE_AGENT_POLICY_TABLE_DEF,
    CONFIG_EFFECTIVE_GLOBAL_POLICY_TABLE_DEF,
    CONFIG_EFFECTIVE_SERVICE_POLICY_TABLE_DEF,
    MODEL_TEMPLATE_TABLE_DEF,
)
from .instance_models import INSTANCE_INFO_TABLE_DEF, SERVICE_INSTANCE_TABLE_DEF

__all__ = [
    "INSTANCE_INFO_TABLE_DEF",
    "SERVICE_INSTANCE_TABLE_DEF",
    "MODEL_TEMPLATE_TABLE_DEF",
    "CONFIG_EFFECTIVE_GLOBAL_POLICY_TABLE_DEF",
    "CONFIG_EFFECTIVE_SERVICE_POLICY_TABLE_DEF",
    "CONFIG_EFFECTIVE_AGENT_POLICY_TABLE_DEF",
    "CONFIG_DEFAULT_TEMPLATE_MAPPING_TABLE_DEF",
]
