# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.

"""Proactive engine — service that scans user conversations, updates the user
profile, and decides whether to proactively reach out with a skill recommendation,
task reminder, or need exploration message.

This is a pure service class that responds to external calls (from CronScheduler
or manual triggers). It does NOT run its own background tick loop.

Runs in AgentServer process. Decision is made by a proactive lightweight agent
(``set_proactive_agent``); the recommendation message is generated by the main
agent — tick triggers it via ``set_trigger_main_agent_callback``, so the message
naturally enters the main agent's context engine and streams to the frontend.

Usage:
- ``engine = ProactiveEngine(config)``
- ``engine.set_proactive_agent(proactive_agent)``
- ``engine.set_trigger_main_agent_callback(callback)``
- ``await engine.tick_now()`` — trigger a recommendation tick
"""

from __future__ import annotations

import logging
import time

from typing import Any

logger = logging.getLogger(__name__)


class ProactiveEngine:
    """Proactive recommendation engine service.

    Each tick:
    1. Build a situation report from multi-session history + profile
    2. Single LLM call (via proactive agent): update profile + decide recommendation type
    3. If a decision is made: trigger main agent to generate message → streams to frontend
       (message naturally enters the main agent's context engine)

    This class does NOT run its own background loop. It is triggered by:
    - CronScheduler (via proactive.tick WebSocket request from Gateway),
      including the "run now" button in the Cron panel (also goes through
      proactive.tick — no separate manual-trigger endpoint).
    """

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        config = config or {}
        self._max_per_day: int = int(config.get("max_recommend_per_day", 5))
        self._max_sessions: int = int(config.get("max_sessions_per_tick", 10))
        # 默认 False，与 config.yaml 的 proactive_recommendation.enabled 默认值一致，
        # 防御性默认=关闭，避免配置段缺失时引擎被误启用。
        self._enabled: bool = config.get("enabled", False)
        self._last_tick_at: float = 0.0
        # 推荐专用 agent：只做决策（无 session、无 tools、单轮、输出 JSON），
        # 替代 proactive_actions._analyze_and_decide 里的裸 model.invoke。
        self._proactive_agent: Any = None
        # 触发主 agent 跑一轮生成话术的回调。
        # 话术交给主 agent 生成 → 自然进其 context engine（save_contexts 持久化）
        # → stream 输出推前端。撤掉旧的 push/inject 回调。
        self._trigger_main_agent_callback: Any = None

    def set_proactive_agent(self, agent: Any) -> None:
        """Set the proactive lightweight agent used for recommendation decision.

        Args:
            agent: A DeepAgent instance (no tools, no task_loop, single-round).
                   Built by app_agentserver via create_deep_agent.
        """
        self._proactive_agent = agent

    @property
    def last_tick_at(self) -> float:
        """Last tick timestamp (public read accessor for ``_last_tick_at``)."""
        return self._last_tick_at

    def rebuild_proactive_agent(self, builder: Any) -> None:
        """Rebuild the proactive agent (e.g. after model config changed).

        The proactive agent is built once at AgentServer startup with the then-
        current model config. When the user changes models (frontend config
        save → agent.reload_config), the main agents hot-reload, but the
        proactive agent would keep the stale model. Call this to rebuild it
        with the latest model config.

        Args:
            builder: Callable ``() -> DeepAgent | None`` (the proactive_adapter
                     ``build_proactive_agent``), re-reads model config at call.
        """
        try:
            new_agent = builder()
            if new_agent is not None:
                self._proactive_agent = new_agent
                logger.info("[ProactiveEngine] proactive agent rebuilt (model config refreshed)")
        except Exception as exc:
            logger.warning("[ProactiveEngine] proactive agent rebuild failed: %s", exc)

    def set_trigger_main_agent_callback(self, callback: Any) -> None:
        """Set the callback that triggers the main agent to run one round.

        Args:
            callback: Async function ``(session_id, channel_id, query, decision) -> bool``.
                      Constructs an AgentRequest with the directive-style query and
                      drives ``adapter.process_message_stream`` so the main agent
                      generates the recommendation message naturally (entering its
                      own context engine + streaming to the frontend). Returns False
                      when the session is busy (避让) or delivery fails.
        """
        self._trigger_main_agent_callback = callback

    def reload_config(self, config: dict[str, Any]) -> None:
        """Hot-reload configuration without restarting the process."""
        new_enabled = bool(config.get("enabled", False))
        new_max_per_day = int(config.get("max_recommend_per_day", self._max_per_day))
        new_max_sessions = int(config.get("max_sessions_per_tick", self._max_sessions))

        self._max_per_day = new_max_per_day
        self._max_sessions = new_max_sessions
        self._enabled = new_enabled
        logger.info("[ProactiveEngine] config reloaded (enabled=%s, max_per_day=%d)",
                   new_enabled, new_max_per_day)

    async def tick_now(self, target_channel: str | None = None) -> bool:
        """Trigger a recommendation tick.

        This is the main API for external callers (CronScheduler, manual triggers).

        Args:
            target_channel: Optional channel ID to deliver the recommendation to.
                          If None, uses the most recently active session.

        Returns:
            True if a recommendation was made, False otherwise.
        """
        if not self._enabled:
            logger.debug("[ProactiveEngine] engine disabled, skipping tick")
            return False

        logger.info("[ProactiveEngine] tick_now called (target_channel=%s)", target_channel)
        try:
            pushed = await self._tick(target_channel=target_channel)
            return bool(pushed)
        except Exception as exc:
            logger.warning("[ProactiveEngine] tick_now failed: %s", exc, exc_info=True)
            return False

    async def _tick(self, target_channel: str | None = None) -> bool:
        """Single tick: build situation → analyze → push.

        Args:
            target_channel: Optional channel ID to deliver the recommendation to.
                          If None, uses the most recently active session.

        Returns:
            True if a recommendation was actually pushed to the channel,
            False if the tick was skipped for any reason (daily limit reached,
            empty situation, no model, no decision, cooldown, no delivery
            target). Callers (CronScheduler / manual trigger) should use this
            to report an accurate status instead of assuming "sent".
        """
        from jiuwenswarm.agents.harness.common.recommendation.proactive_actions import (
            _today_recommend_count,
            _increment_daily_count,
            _is_cooled_down,
            _mark_recommended,
            _get_all_skills,
            _analyze_and_decide,
            _trigger_main_agent,
        )
        from jiuwenswarm.agents.harness.common.recommendation.profile_extractor import (
            load_user_profile,
            save_user_profile,
        )
        from jiuwenswarm.agents.harness.common.recommendation.situation_report import (
            build_situation_report,
        )

        # 每次 tick 顺手清理过期数据（daily_counts 老日期 key、cooldown_records 过期项）。
        # 这些数据只增不减，不清理会长期累积（user_profile.json 越来越大）。
        try:
            self.run_maintenance()
        except Exception as exc:
            logger.debug("[ProactiveEngine] maintenance failed: %s", exc)

        # Gate: daily budget (skip for manual triggers)
        if _today_recommend_count() >= self._max_per_day:
            logger.debug("[ProactiveEngine] daily limit reached, skipping tick")
            self._last_tick_at = time.time()
            return False

        # ── Step 1: Build situation report ─────────────────────
        # build_situation_report 默认只扫 agent 类会话（mode_prefix="agent"），
        # 避免 code/team 会话的技术语境污染推荐决策。
        _, available_skills = _get_all_skills()
        report = await build_situation_report(
            max_sessions=self._max_sessions,
            skills=available_skills,
        )

        if report.is_empty():
            logger.debug("[ProactiveEngine] situation report empty, skipping tick")
            self._last_tick_at = time.time()
            return False

        report_text = report.render_for_llm()

        # ── Step 2: LLM analysis + decision ────────────────────
        # 决策由专用 agent 生成（替代裸 model.invoke），无 session、单轮、输出 JSON。
        profile = load_user_profile()
        if self._proactive_agent is None:
            logger.debug("[ProactiveEngine] no proactive agent available, skipping tick")
            self._last_tick_at = time.time()
            return False

        result = await _analyze_and_decide(
            report_text, profile, available_skills, self._proactive_agent,
        )

        # ── Step 3: Update profile ─────────────────────────────
        if result.profile_delta:
            profile.merge(result.profile_delta)
            save_user_profile(profile)

        # ── Step 4: Check if we have a recommendation ───────────
        decision = result.decision
        if not decision:
            logger.debug("[ProactiveEngine] no recommendation this tick")
            self._last_tick_at = time.time()
            return False

        # ── Step 5: Cooldown check ─────────────────────────────
        if not _is_cooled_down(decision.target, profile):
            logger.debug("[ProactiveEngine] '%s' still in cooldown, skipping", decision.target)
            self._last_tick_at = time.time()
            return False

        # ── Step 6: Pick delivery target ───────────────────────
        if target_channel:
            target_session = report.find_session_for_channel(target_channel)
            if not target_session:
                logger.debug("[ProactiveEngine] no session found for channel '%s'", target_channel)
                self._last_tick_at = time.time()
                return False
        else:
            target_session = report.most_recent_active_session()
            if not target_session:
                logger.debug("[ProactiveEngine] no active session for delivery")
                self._last_tick_at = time.time()
                return False

        # ── Step 7: Trigger main agent to generate & deliver ────
        # 把决策包成指令式 query 触发主 agent 跑一轮，主 agent 自己生成话术
        # → 进其 context engine（save_contexts 持久化）→ stream 输出推前端。
        # 避让：目标 session 正忙则跳过本次 tick。
        if self._trigger_main_agent_callback is None:
            logger.warning("[ProactiveEngine] no trigger_main_agent_callback, skipping")
            self._last_tick_at = time.time()
            return False

        delivered = await _trigger_main_agent(
            session_id=target_session.session_id,
            channel_id=target_channel,
            decision=decision,
            trigger_callback=self._trigger_main_agent_callback,
        )
        if not delivered:
            logger.info("[ProactiveEngine] not delivered (session busy or trigger failed), skipping")
            self._last_tick_at = time.time()
            return False

        # ── Step 8: Update state ────────────────────────────────
        _increment_daily_count()
        _mark_recommended(decision.target, profile)
        profile.add_recommendation({
            "type": decision.type,
            "target": decision.target,
            "reason": decision.reason,
            "urgency": decision.urgency,
            "tick_at": time.time(),
            "session_id": target_session.session_id,
        })

        save_user_profile(profile)
        self._last_tick_at = time.time()

        logger.info("[ProactiveEngine] delivered '%s' (type=%s, urgency=%.2f, session=%s)",
                     decision.target, decision.type, decision.urgency,
                     target_session.session_id[:20])
        return True

    # ── Maintenance helpers (called by Cron or manually) ─────────

    @staticmethod
    def run_maintenance() -> None:
        """Prune stale data from daily counts and cooldown records.

        This should be called periodically (e.g., by Cron) to keep the
        recommendation state clean.
        """
        from jiuwenswarm.agents.harness.common.recommendation.proactive_actions import (
            _prune_daily_counts,
            _prune_cooldown_records,
        )
        from jiuwenswarm.agents.harness.common.recommendation.profile_extractor import (
            load_user_profile,
            save_user_profile,
        )

        _prune_daily_counts()
        profile = load_user_profile()
        _prune_cooldown_records(profile)
        save_user_profile(profile)
        logger.debug("[ProactiveEngine] maintenance completed")
