apiVersion: v1
kind: Service
metadata:
  name: <<GATEWAY_NAME>>
  namespace: <<NAMESPACE>>
spec:
  selector:
    app: <<GATEWAY_NAME>> # 必须匹配你的 gateway pod 的标签
  ports:
    - port: 19000           # Service 端口
      targetPort: 19000     # 容器端口
  type: ClusterIP           # 集群内部访问，不需要外网
