"""Bidirectional beam planner for Symphony score orchestration."""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import mimetypes
import re
from collections import defaultdict
from dataclasses import dataclass
from typing import Any, Awaitable, Callable, Protocol, Sequence

from jiuwenswarm.symphony.llm import LLMConfig, create_llm_client, llm_usage_context
from jiuwenswarm.symphony.orchestration.artifacts import ScoreArtifacts
from jiuwenswarm.symphony.orchestration.language import (
    default_beam_plan_title,
    planner_language_instruction,
    resolve_orchestration_language,
)
from jiuwenswarm.symphony.orchestration.planning.models import (
    GroundedQuery,
    OrchestrationPlan,
    SearchState,
)
from jiuwenswarm.symphony.orchestration.planning.plan_builder import (
    build_incoming_edges,
    build_outgoing_edges,
    edge_plan_item,
    state_to_plan,
)
from jiuwenswarm.symphony.orchestration.planning.utils import skill_id

JUDGEMENT_SCORE_THRESHOLD = 0.5
DEFAULT_MAX_CONCURRENT_JUDGES = 3
BEAM_DEFAULT_MAX_SKILLS = 40
BeamProgressCallback = Callable[[dict[str, Any]], Awaitable[None] | None]
logger = logging.getLogger(__name__)
_EXPLICIT_FILE_EXTENSION_RE = re.compile(
    r"(?<![A-Za-z0-9])[\w.-]+\.([A-Za-z0-9]{1,12})\b"
)
_MIME_TO_OUTPUT_TYPE = {
    "application/json": "json",
    "application/msword": "docx",
    "application/pdf": "pdf",
    "application/vnd.ms-excel": "xlsx",
    "application/vnd.ms-powerpoint": "pptx",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": (
        "pptx"
    ),
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "docx",
    "text/csv": "csv",
    "text/html": "html",
}
_EXTENSION_MIME_TYPES = {
    ".doc": "application/msword",
    ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".ppt": "application/vnd.ms-powerpoint",
    ".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ".xls": "application/vnd.ms-excel",
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
}
for _extension, _mime_type in _EXTENSION_MIME_TYPES.items():
    mimetypes.add_type(_mime_type, _extension)

BEAM_JUDGE_SYSTEM_PROMPT = """You are a task orchestration judge.
Your job is to score candidate Skills for expanding a partial task plan during
bidirectional beam search.
Return strict JSON only.

You receive:
- The user's task request.
- The current Skill in the partial plan.
- A search direction: forward or backward.
- Candidate Skills connected by existing can_feed edges.

Task:
- Score each candidate from 0.0 to 1.0 for how useful it is for completing the
  user's task as part of the partial plan.
- Treat data dependency as already validated by can_feed edges; do not judge edge
  feasibility.
- Prefer candidates that help satisfy explicit user requirements, including
  requested output formats.
- Do not invent Skills, inputs, outputs, or edge relationships.
- Keep reason very short: <= 50 Chinese characters or <= 12 English words.

Schema:
{
  "judgements": [
    {"candidate_id": "candidate-id", "score": 0.0, "reason": "short reason"}
  ]
}
"""

BEAM_FINAL_RERANK_SYSTEM_PROMPT = """You are a final task orchestration reranker.
Return strict JSON only.

You receive:
- The user's task request.
- Candidate plans generated by bidirectional beam search.
- A candidate Skill pool containing all Skills from those candidate plans.
- Retrieval seed Skill IDs.
- Required output types explicitly requested by the user.
- Compact hit signals for each plan.

Task:
- Select the best primary plan for completing the user's task.
- If candidate plans are useful but incomplete, return the best partial plan.
- Candidate plans are reference paths, not hard constraints for the final plan.
- Select final steps from candidate_skill_pool to cover the user's task.
- You may lightly edit by merging Skills from candidate plans, pruning only
  identical Skills or clearly similar-function duplicate Skills.
- Use only Skill IDs already present in the candidate plans.
- Retrieval seed Skill IDs are strong evidence from retrieval.
- Retrieval seeds are the starting points; graph-expanded Skills are additional
  candidates found through the can_feed graph.
- Prefer core delivery Skills and requested output formats.
- For multi-deliverable or multi-stage tasks, preserve parallel core Skills even
  when they do not have a direct can_feed edge between them.
- can_feed edges express execution dependencies; missing can_feed edges do not
  mean two Skills cannot both belong in the final plan.
- Prefer preserving retrieval seed Skills that are relevant to the user's task.
- Drop a retrieval seed Skill only when it duplicates another selected Skill with
  the same or clearly similar function.
- Preserve a retrieval seed Skill in a partial plan when it directly helps data
  collection, computation, generation, presentation, or requested output
  delivery.
- When the task has multiple distinct requirements, prefer a plan that preserves
  useful retrieval seeds and adds relevant graph-expanded Skills.
- A slightly longer plan is acceptable when the added Skill directly helps data
  collection, computation, generation, presentation, or requested output
  delivery.
- Preserve auxiliary Skills unless they duplicate another selected Skill with the
  same or clearly similar function.
- Do not replace a core delivery Skill with an auxiliary Skill.
- Prefer the shortest plan that satisfies the user's intent.
- Prefer provided can_feed edges; infer a missing relationship only when needed
  to connect selected steps.
- Do not invent Skills, inputs, outputs, or final artifacts.
- Keep each reason <= 50 Chinese characters or <= 12 English words.

Schema:
{
  "selected_plan_index": 1,
  "reason": "short reason",
  "steps": [
    {"skill_id": "skill-a", "reason": "short reason"}
  ],
  "can_feed_edges": [
    {"source_id": "skill-a", "target_id": "skill-b", "reason": "short reason"}
  ]
}
"""


@dataclass(frozen=True)
class BeamState:
    """One bidirectional beam search state."""

    skill_ids: tuple[str, ...]
    edge_indices: tuple[int, ...]
    available: frozenset[tuple[str, str]]
    judgement_scores: tuple[float, ...]
    score_reasons: tuple[str, ...]
    seed_skill_ids: tuple[str, ...]
    directions: frozenset[str]

    @property
    def depth(self) -> int:
        return len(self.skill_ids)

    @property
    def head(self) -> str:
        return self.skill_ids[0]

    @property
    def tail(self) -> str:
        return self.skill_ids[-1]

    def to_search_state(self) -> SearchState:
        return SearchState(
            skill_ids=self.skill_ids,
            available=self.available,
            edges=self.edge_indices,
            score_reasons=self.score_reasons,
        )


@dataclass(frozen=True)
class NeighborExpansion:
    """A single adjacent Skill candidate to be judged."""

    candidate_id: str
    state: BeamState
    direction: str
    current_skill_id: str
    candidate_skill_id: str
    edge_index: int


@dataclass(frozen=True)
class PlannerJudgement:
    """LLM judgement for one neighbor expansion."""

    candidate_id: str
    score: float
    reason: str


@dataclass(frozen=True)
class SubtreeCacheEntry:
    """Accepted neighbor expansion reusable from the same current Skill."""

    candidate_skill_id: str
    edge_index: int
    judgement_score: float
    reason: str


_GRAPH_STATUS_PRIORITY = {
    "pending": 0,
    "rejected": 1,
    "seed": 2,
    "selected": 3,
    "final": 4,
}


class BeamSearchGraph:
    """Lightweight search graph for user-facing beam progress."""

    def __init__(
        self,
        skill_by_id: dict[str, dict[str, Any]],
        edges: list[dict[str, Any]],
    ) -> None:
        self.skill_by_id = skill_by_id
        self.edges = edges
        self.nodes: dict[str, dict[str, Any]] = {}
        self.graph_edges: dict[str, dict[str, Any]] = {}

    def add_seed(self, current_skill_id: str) -> None:
        self._ensure_node(current_skill_id, status="seed", direction="seed", seed=True)

    def add_candidate(self, expansion: NeighborExpansion) -> dict[str, Any]:
        self._ensure_node(
            expansion.current_skill_id,
            status="seed" if self._is_seed(expansion.current_skill_id) else "selected",
            direction=expansion.direction,
        )
        candidate = self._ensure_node(
            expansion.candidate_skill_id,
            status="pending",
            direction=expansion.direction,
        )
        edge = self._ensure_edge(expansion, status="pending")
        return {
            "current_skill_id": expansion.current_skill_id,
            "candidate_skill_id": expansion.candidate_skill_id,
            "candidate_label": candidate["label"],
            "direction": expansion.direction,
            "status": "pending",
            "edge": edge,
        }

    def apply_judgement(
        self,
        expansion: NeighborExpansion,
        judgement: PlannerJudgement,
    ) -> dict[str, Any]:
        status = (
            "selected"
            if judgement.score >= JUDGEMENT_SCORE_THRESHOLD
            else "rejected"
        )
        candidate = self._ensure_node(
            expansion.candidate_skill_id,
            status=status,
            direction=expansion.direction,
        )
        edge = self._ensure_edge(expansion, status=status)
        return {
            "current_skill_id": expansion.current_skill_id,
            "candidate_skill_id": expansion.candidate_skill_id,
            "candidate_label": candidate["label"],
            "direction": expansion.direction,
            "status": status,
            "edge": edge,
        }

    def mark_final_plan(self, plan: dict[str, Any]) -> dict[str, Any]:
        final_skill_ids: list[str] = []
        for step in plan.get("steps") or []:
            if not isinstance(step, dict):
                continue
            current_skill_id = str(step.get("skill_id") or "").strip()
            if not current_skill_id:
                continue
            self._ensure_node(current_skill_id, status="final", direction="final")
            final_skill_ids.append(current_skill_id)

        final_edge_ids: list[str] = []
        for edge in plan.get("can_feed_edges") or []:
            if not isinstance(edge, dict):
                continue
            source_id = str(edge.get("source_id") or edge.get("source") or "").strip()
            target_id = str(edge.get("target_id") or edge.get("target") or "").strip()
            edge_id = self._existing_edge_id(source_id, target_id)
            if not edge_id:
                continue
            self.graph_edges[edge_id]["status"] = _dominant_status(
                str(self.graph_edges[edge_id].get("status") or ""),
                "final",
            )
            final_edge_ids.append(edge_id)

        return {
            "final_skill_ids": list(dict.fromkeys(final_skill_ids)),
            "final_edge_ids": list(dict.fromkeys(final_edge_ids)),
        }

    def snapshot(self) -> dict[str, Any]:
        nodes = []
        for node in self.nodes.values():
            directions = sorted(node.get("directions") or [])
            nodes.append(
                {
                    "id": node["id"],
                    "label": node["label"],
                    "status": node["status"],
                    "seed": bool(node.get("seed")),
                    "direction": _direction_label(directions),
                }
            )
        edges = [
            _copy_public_graph_edge(edge)
            for edge in self.graph_edges.values()
        ]
        return {"nodes": nodes, "edges": edges}

    def _ensure_node(
        self,
        current_skill_id: str,
        *,
        status: str,
        direction: str,
        seed: bool = False,
    ) -> dict[str, Any]:
        node = self.nodes.get(current_skill_id)
        if node is None:
            node = {
                "id": current_skill_id,
                "label": _skill_label(self.skill_by_id.get(current_skill_id, {})),
                "status": status,
                "seed": seed,
                "directions": set(),
            }
            self.nodes[current_skill_id] = node
        else:
            node["status"] = _dominant_status(str(node.get("status") or ""), status)
            node["seed"] = bool(node.get("seed")) or seed
        if direction:
            node["directions"].add(direction)
        return node

    def _ensure_edge(
        self,
        expansion: NeighborExpansion,
        *,
        status: str,
    ) -> dict[str, Any]:
        edge = self.edges[expansion.edge_index]
        source_id = expansion.current_skill_id
        target_id = expansion.candidate_skill_id
        edge_id = f"{source_id}->{target_id}"
        graph_edge = self.graph_edges.get(edge_id)
        confidence = edge.get("confidence")
        if graph_edge is None:
            graph_edge = {
                "id": edge_id,
                "source": source_id,
                "target": target_id,
                "status": status,
                "confidence": confidence,
                "direction": expansion.direction,
                "can_feed_source_id": skill_id(edge.get("source")),
                "can_feed_target_id": skill_id(edge.get("target")),
            }
            self.graph_edges[edge_id] = graph_edge
        else:
            graph_edge["status"] = _dominant_status(
                str(graph_edge.get("status") or ""),
                status,
            )
            graph_edge["confidence"] = _max_confidence(
                graph_edge.get("confidence"),
                confidence,
            )
        return _copy_public_graph_edge(graph_edge)

    def _existing_edge_id(self, source_id: str, target_id: str) -> str:
        forward_id = f"{source_id}->{target_id}"
        if forward_id in self.graph_edges:
            return forward_id
        backward_id = f"{target_id}->{source_id}"
        if backward_id in self.graph_edges:
            return backward_id
        return ""

    def _is_seed(self, current_skill_id: str) -> bool:
        node = self.nodes.get(current_skill_id)
        return bool(node and node.get("seed"))


class PlannerJudgementCache:
    """Cache judgements by the local planning context visible to the LLM."""

    def __init__(self) -> None:
        self._items: dict[tuple[str, str, str, str], PlannerJudgement] = {}
        self.hits = 0
        self.misses = 0

    def get(
        self,
        query_signature: str,
        expansion: NeighborExpansion,
    ) -> PlannerJudgement | None:
        key = self.key_for(query_signature, expansion)
        cached = self._items.get(key)
        if cached is None:
            self.misses += 1
            return None
        self.hits += 1
        return cached

    def set(
        self,
        query_signature: str,
        expansion: NeighborExpansion,
        judgement: PlannerJudgement,
    ) -> None:
        self._items[self.key_for(query_signature, expansion)] = judgement

    @staticmethod
    def key_for(
        query_signature: str,
        expansion: NeighborExpansion,
    ) -> tuple[str, str, str, str]:
        return (
            query_signature,
            expansion.direction,
            expansion.current_skill_id,
            expansion.candidate_skill_id,
        )


class BeamJudgeQueue:
    """Run grouped LLM judgement tasks with a global concurrency limit."""

    def __init__(
        self,
        *,
        planner: BidirectionalBeamPlannerProtocol,
        max_concurrent_judges: int = DEFAULT_MAX_CONCURRENT_JUDGES,
    ) -> None:
        self.planner = planner
        self._semaphore = asyncio.Semaphore(max(1, int(max_concurrent_judges)))
        self.llm_call_count = 0
        self.failures: list[str] = []

    async def judge_groups(
        self,
        query: str,
        groups: list[list[NeighborExpansion]],
    ) -> dict[str, PlannerJudgement]:
        tasks = [
            asyncio.create_task(self._judge_group(query, group))
            for group in groups
            if group
        ]
        if not tasks:
            return {}

        output: dict[str, PlannerJudgement] = {}
        for result in await asyncio.gather(*tasks):
            output.update(result)
        return output

    async def _judge_group(
        self,
        query: str,
        group: list[NeighborExpansion],
    ) -> dict[str, PlannerJudgement]:
        async with self._semaphore:
            self.llm_call_count += 1
            try:
                return await self.planner.judge_expansions(query, group)
            except Exception as exc:
                candidates = ", ".join(item.candidate_id for item in group[:5])
                self.failures.append(
                    f"beam judge failed for candidates [{candidates}]: {exc}"
                )
                return {}


class BidirectionalBeamPlannerProtocol(Protocol):
    async def judge_expansions(
        self,
        query: str,
        expansions: list[NeighborExpansion],
    ) -> dict[str, PlannerJudgement]:
        ...


class BidirectionalBeamPlanner:
    """Build candidate plans through judgement-guided bidirectional beam search."""

    def __init__(
        self,
        artifacts: ScoreArtifacts,
        *,
        llm_config: LLMConfig | None,
        llm_client: Any | None,
        min_edge_confidence: float,
        top_k: int,
        max_depth: int,
        candidate_skill_ids: Sequence[str] | None = None,
        max_concurrent_judges: int = DEFAULT_MAX_CONCURRENT_JUDGES,
        progress_callback: BeamProgressCallback | None = None,
        language: str = "cn",
    ) -> None:
        self.artifacts = artifacts
        self.llm_config = llm_config
        self.llm_client = llm_client
        self.min_edge_confidence = min_edge_confidence
        self.top_k = max(1, int(top_k))
        self.max_depth = max(1, int(max_depth))
        self.max_concurrent_judges = max(1, int(max_concurrent_judges))
        self.skill_by_id = artifacts.skill_by_id
        self.candidate_skill_ids = self._normalize_candidate_skill_ids(
            candidate_skill_ids,
            known_skill_ids=set(self.skill_by_id),
        )
        self.progress_callback = progress_callback
        self.language = resolve_orchestration_language(language)
        self._beam_event_sequence = 0
        self._beam_events: list[dict[str, Any]] = []
        self.eligible_edges = self._sorted_eligible_edges()
        self._beam_graph = BeamSearchGraph(self.skill_by_id, self.eligible_edges)
        self.outgoing_edges = build_outgoing_edges(self.eligible_edges)
        self.incoming_edges = build_incoming_edges(self.eligible_edges)
        self.cache = PlannerJudgementCache()
        self.required_output_types: frozenset[str] = frozenset()
        self.effective_top_k = self._effective_top_k()
        self.subtree_cache: dict[
            tuple[str, str, str],
            tuple[SubtreeCacheEntry, ...],
        ] = {}
        self.subtree_cache_hits = 0
        self.subtree_cache_misses = 0

    async def plan(self, query: str) -> dict[str, Any]:
        client = self._client()
        del client
        self._reset_beam_progress()
        self.required_output_types = _required_output_types_from_query(query)
        self._reset_subtree_cache()
        query_signature = _query_signature(query)
        initial_states = self._initial_states()
        frontier = initial_states
        all_states = list(initial_states)
        seed_skill_ids = tuple(state.skill_ids[0] for state in frontier)
        for current_skill_id in seed_skill_ids:
            self._beam_graph.add_seed(current_skill_id)
        await self._emit_beam_event(
            "started",
            round_index=0,
            payload={
                "seed_skill_ids": list(seed_skill_ids),
                "effective_top_k": self.effective_top_k,
                "graph": self._beam_graph.snapshot(),
            },
        )
        rounds: list[dict[str, Any]] = []
        judge_queue = BeamJudgeQueue(
            planner=self,
            max_concurrent_judges=self.max_concurrent_judges,
        )

        for _round in range(max(0, self.max_depth - 1)):
            groups, cached, subtree_states = self._expansion_groups(
                query_signature,
                frontier,
            )
            found = self._record_candidates_found()
            if found:
                await self._emit_beam_event(
                    "candidates_found",
                    round_index=_round + 1,
                    payload={
                        "expansions": found,
                        "graph": self._beam_graph.snapshot(),
                    },
                )
            if not groups and not cached:
                if subtree_states:
                    merged_states = self._merge_states(subtree_states)
                    retained = self._rank_and_trim(
                        merged_states,
                        limit=self.effective_top_k,
                    )
                    all_states = self._rank_and_trim(
                        [*all_states, *merged_states],
                        limit=self._final_candidate_limit(),
                    )
                    frontier = retained
                    continue
                break
            fresh = await judge_queue.judge_groups(query, groups)
            fresh = self._apply_judgement_aliases(fresh)
            for candidate_id, judgement in fresh.items():
                expansion = self._expansion_by_id(candidate_id)
                if expansion is not None:
                    self.cache.set(query_signature, expansion, judgement)
            judgements = {**cached, **fresh}
            self._record_subtree_judgements(query_signature, judgements)
            judged = self._record_candidates_judged(judgements)
            if judged:
                await self._emit_beam_event(
                    "candidates_judged",
                    round_index=_round + 1,
                    payload={
                        "candidates": judged,
                        "graph": self._beam_graph.snapshot(),
                    },
                )
            next_states = [
                *subtree_states,
                *self._apply_judgements(judgements),
            ]
            if not next_states:
                rounds.append(
                    self._round_summary(
                        round_index=_round + 1,
                        frontier=frontier,
                        groups=groups,
                        cached=cached,
                        judgements=judgements,
                        retained=[],
                    )
                )
                await self._emit_beam_event(
                    "graph_merged",
                    round_index=_round + 1,
                    payload={
                        "retained_paths": [],
                        "graph": self._beam_graph.snapshot(),
                    },
                )
                break
            merged_states = self._merge_states(next_states)
            retained = self._rank_and_trim(
                merged_states,
                limit=self.effective_top_k,
            )
            rounds.append(
                self._round_summary(
                    round_index=_round + 1,
                    frontier=frontier,
                    groups=groups,
                    cached=cached,
                    judgements=judgements,
                    retained=retained,
                )
            )
            all_states = self._rank_and_trim(
                [*all_states, *merged_states],
                limit=self._final_candidate_limit(),
            )
            frontier = retained
            await self._emit_beam_event(
                "graph_merged",
                round_index=_round + 1,
                payload={
                    "retained_paths": [
                        self._state_summary(state, rank=index)
                        for index, state in enumerate(retained, start=1)
                    ],
                    "graph": self._beam_graph.snapshot(),
                },
            )

        final_states = self._final_candidate_states(
            searched_states=all_states,
            seed_states=initial_states,
        )
        plans = self._plans_from_states(final_states)[: self._final_candidate_limit()]
        recommended_plans = [self._plan_payload(plan, query=query) for plan in plans]
        final_rerank = await self._final_rerank_plans(
            query=query,
            recommended_plans=recommended_plans,
            seed_skill_ids=seed_skill_ids,
        )
        recommended_plans = final_rerank["recommended_plans"]
        final_plan = recommended_plans[0] if recommended_plans else {}
        final_graph_payload = self._beam_graph.mark_final_plan(final_plan)
        await self._emit_beam_event(
            "completed",
            round_index=len(rounds),
            payload={
                **final_graph_payload,
                "graph": self._beam_graph.snapshot(),
            },
        )
        status = recommended_plans[0]["status"] if recommended_plans else "no_plan"
        reason = recommended_plans[0].get("reason", "") if recommended_plans else ""
        final_plan_hits = (
            self._compact_plan_for_rerank(
                final_plan,
                plan_index=1,
                seed_skill_ids=seed_skill_ids,
            )
            if final_plan
            else {}
        )
        unique_skill_ids = {
            current_skill_id
            for state in final_states
            for current_skill_id in state.skill_ids
        }
        return {
            "query": query,
            "language": self.language,
            "score_dir": str(self.artifacts.score_dir),
            "planning_mode": "bidirectional_beam",
            "llm_call_count": judge_queue.llm_call_count,
            "candidate_skill_count": len(unique_skill_ids),
            "candidate_edge_count": len(self.eligible_edges),
            "plans": recommended_plans,
            "recommended_plans": recommended_plans,
            "ranking_mode": "bidirectional_beam",
            "beam_search": {
                "mode": "bidirectional_beam",
                "language": self.language,
                "round_index": len(rounds),
                "top_k": self.top_k,
                "effective_top_k": self.effective_top_k,
                "max_depth": self.max_depth,
                "min_edge_confidence": self.min_edge_confidence,
                "judgement_score_threshold": JUDGEMENT_SCORE_THRESHOLD,
                "max_concurrent_judges": self.max_concurrent_judges,
                "subtree_cache_hits": self.subtree_cache_hits,
                "subtree_cache_misses": self.subtree_cache_misses,
                "final_rerank_enabled": final_rerank["enabled"],
                "final_rerank_applied": final_rerank["applied"],
                "final_rerank_guard_applied": final_rerank["guard_applied"],
                "final_rerank_guard_reason": final_rerank["guard_reason"],
                "final_rerank_reason": final_rerank["reason"],
                "final_rerank_error": final_rerank["error"],
                "final_rerank_cross_plan_skill_merge": (
                    final_rerank["cross_plan_skill_merge"]
                ),
                "seed_hits": final_plan_hits.get("seed_hits", []),
                "graph_expansion_hits": final_plan_hits.get(
                    "graph_expansion_hits",
                    [],
                ),
                "output_hits": final_plan_hits.get("output_hits", []),
                "seed_skill_ids": list(seed_skill_ids),
                "graph": self._beam_graph.snapshot(),
                "rounds": rounds,
                "events": self._beam_events,
                "retained_paths": [
                    self._state_summary(state, rank=index)
                    for index, state in enumerate(final_states, start=1)
                ],
            },
            "decision": {
                "mode": "bidirectional_beam",
                "strategy": "judgement_bidirectional_beam",
                "validated_count": len(recommended_plans),
                "candidate_count": len(unique_skill_ids),
                "judge_cache_hits": self.cache.hits,
                "judge_cache_misses": self.cache.misses,
                "final_rerank_enabled": final_rerank["enabled"],
                "final_rerank_applied": final_rerank["applied"],
                "final_rerank_guard_applied": final_rerank["guard_applied"],
                "final_rerank_guard_reason": final_rerank["guard_reason"],
                "final_rerank_reason": final_rerank["reason"],
                "final_rerank_error": final_rerank["error"],
                "final_rerank_cross_plan_skill_merge": (
                    final_rerank["cross_plan_skill_merge"]
                ),
                "seed_hits": final_plan_hits.get("seed_hits", []),
                "graph_expansion_hits": final_plan_hits.get(
                    "graph_expansion_hits",
                    [],
                ),
                "output_hits": final_plan_hits.get("output_hits", []),
            },
            "validation": {
                "valid": True,
                "details": judge_queue.failures[:10],
            },
            "status": status,
            "reason": reason,
        }

    async def judge_expansions(
        self,
        query: str,
        expansions: list[NeighborExpansion],
    ) -> dict[str, PlannerJudgement]:
        if not expansions:
            return {}

        first = expansions[0]
        current_skill = self.skill_by_id.get(first.current_skill_id, {})
        payload = {
            "query": query,
            "direction": first.direction,
            "current_skill": self._skill_payload(current_skill),
            "candidates": [
                self._candidate_payload(expansion)
                for expansion in expansions
            ],
        }
        with llm_usage_context("orchestration", "bidirectional_beam_judgement"):
            raw = await self._client().complete_json_async(
                system_prompt=(
                    f"{BEAM_JUDGE_SYSTEM_PROMPT}\n"
                    f"{planner_language_instruction(self.language)}"
                ),
                user_content=json.dumps(payload, ensure_ascii=False),
                error_context="Symphony bidirectional beam judgement",
                request_overrides={
                    "extra_body": {"thinking": {"type": "disabled"}},
                },
            )
        data = json.loads(raw)
        items = data.get("judgements") if isinstance(data, dict) else data
        if not isinstance(items, list):
            return {}

        known_ids = {expansion.candidate_id for expansion in expansions}
        judgements: dict[str, PlannerJudgement] = {}
        for item in items:
            if not isinstance(item, dict):
                continue
            candidate_id = str(item.get("candidate_id") or "").strip()
            if candidate_id not in known_ids:
                continue
            score = _clamp_score(item.get("score"))
            judgements[candidate_id] = PlannerJudgement(
                candidate_id=candidate_id,
                score=score,
                reason=str(item.get("reason") or "").strip(),
            )
        return judgements

    async def _final_rerank_plans(
        self,
        *,
        query: str,
        recommended_plans: list[dict[str, Any]],
        seed_skill_ids: tuple[str, ...],
    ) -> dict[str, Any]:
        base = {
            "enabled": bool(recommended_plans),
            "applied": False,
            "guard_applied": False,
            "guard_reason": "",
            "reason": "",
            "error": "",
            "cross_plan_skill_merge": False,
            "recommended_plans": recommended_plans[: self.effective_top_k],
        }
        if not recommended_plans:
            return base

        prompt_payload = self._final_rerank_payload(
            query=query,
            recommended_plans=recommended_plans,
            seed_skill_ids=seed_skill_ids,
        )
        try:
            with llm_usage_context("orchestration", "beam_final_rerank"):
                raw = await self._client().complete_json_async(
                    system_prompt=(
                        f"{BEAM_FINAL_RERANK_SYSTEM_PROMPT}\n"
                        f"{planner_language_instruction(self.language)}"
                    ),
                    user_content=json.dumps(prompt_payload, ensure_ascii=False),
                    error_context="Symphony beam final rerank",
                    request_overrides={
                        "extra_body": {"thinking": {"type": "disabled"}},
                    },
                )
            selection = json.loads(raw)
        except Exception as exc:
            return {**base, "error": f"{type(exc).__name__}: {exc}"}
        if not isinstance(selection, dict):
            return {**base, "error": "Final rerank returned non-object JSON."}

        materialized = self._materialize_final_rerank(
            selection,
            recommended_plans=recommended_plans,
        )
        if not materialized["valid"]:
            return {**base, "error": materialized["detail"]}

        primary_plan = materialized["plan"]
        guard_result = self._final_rerank_seed_loss_guard(
            primary_plan,
            recommended_plans[0],
            seed_skill_ids=seed_skill_ids,
        )
        if guard_result["guard_applied"]:
            return {
                **base,
                "guard_applied": True,
                "guard_reason": guard_result["reason"],
                "error": guard_result["reason"],
            }
        output = [primary_plan]
        seen = {_dict_plan_signature(primary_plan)}
        for plan in recommended_plans:
            signature = _dict_plan_signature(plan)
            if signature in seen:
                continue
            output.append(plan)
            seen.add(signature)
            if len(output) >= self.effective_top_k:
                break
        return {
            **base,
            "applied": True,
            "reason": _short_text(str(selection.get("reason") or "")),
            "cross_plan_skill_merge": materialized["cross_plan_skill_merge"],
            "recommended_plans": output,
        }

    def _final_rerank_seed_loss_guard(
        self,
        primary_plan: dict[str, Any],
        original_top_plan: dict[str, Any],
        *,
        seed_skill_ids: tuple[str, ...],
    ) -> dict[str, Any]:
        primary_signals = self._plan_signal_counts(
            primary_plan,
            seed_skill_ids=seed_skill_ids,
        )
        original_signals = self._plan_signal_counts(
            original_top_plan,
            seed_skill_ids=seed_skill_ids,
        )
        loses_seeds = primary_signals["seed_hits"] < original_signals["seed_hits"]
        no_output_compensation = (
            primary_signals["output_hits"] <= original_signals["output_hits"]
        )
        no_graph_compensation = (
            primary_signals["graph_expansion_hits"]
            <= original_signals["graph_expansion_hits"]
        )
        if loses_seeds and no_output_compensation and no_graph_compensation:
            return {
                "guard_applied": True,
                "reason": (
                    "Final rerank rejected because primary plan loses retrieval "
                    "seed coverage without output or graph expansion compensation."
                ),
            }
        return {"guard_applied": False, "reason": ""}

    def _plan_signal_counts(
        self,
        plan: dict[str, Any],
        *,
        seed_skill_ids: tuple[str, ...],
    ) -> dict[str, int]:
        skill_ids = [
            str(step.get("skill_id") or "").strip()
            for step in plan.get("steps") or []
            if isinstance(step, dict) and str(step.get("skill_id") or "").strip()
        ]
        seed_skill_id_set = set(seed_skill_ids)
        produced_types = {
            str(item.get("type") or "").strip().lower()
            for item in plan.get("produced_artifacts") or []
            if isinstance(item, dict)
        }
        return {
            "seed_hits": len(
                {
                    current_skill_id
                    for current_skill_id in skill_ids
                    if current_skill_id in seed_skill_id_set
                }
            ),
            "graph_expansion_hits": len(
                {
                    current_skill_id
                    for current_skill_id in skill_ids
                    if current_skill_id not in seed_skill_id_set
                }
            ),
            "output_hits": len(self.required_output_types & produced_types),
        }

    def _final_rerank_payload(
        self,
        *,
        query: str,
        recommended_plans: list[dict[str, Any]],
        seed_skill_ids: tuple[str, ...],
    ) -> dict[str, Any]:
        return {
            "query": query,
            "retrieval_seed_skill_ids": list(seed_skill_ids),
            "required_output_types": sorted(self.required_output_types),
            "candidate_skill_pool": self._candidate_skill_pool_for_rerank(
                recommended_plans,
                seed_skill_ids=seed_skill_ids,
            ),
            "candidate_plans": [
                self._compact_plan_for_rerank(
                    plan,
                    plan_index=index,
                    seed_skill_ids=seed_skill_ids,
                )
                for index, plan in enumerate(recommended_plans, start=1)
            ],
        }

    def _compact_plan_for_rerank(
        self,
        plan: dict[str, Any],
        *,
        plan_index: int,
        seed_skill_ids: tuple[str, ...],
    ) -> dict[str, Any]:
        skill_ids = [
            str(step.get("skill_id") or "").strip()
            for step in plan.get("steps") or []
            if isinstance(step, dict) and str(step.get("skill_id") or "").strip()
        ]
        produced_types = {
            str(item.get("type") or "").strip().lower()
            for item in plan.get("produced_artifacts") or []
            if isinstance(item, dict)
        }
        return {
            "plan_index": plan_index,
            "skills": skill_ids,
            "seed_hits": [
                current_skill_id
                for current_skill_id in skill_ids
                if current_skill_id in seed_skill_ids
            ],
            "graph_expansion_hits": [
                current_skill_id
                for current_skill_id in skill_ids
                if current_skill_id not in seed_skill_ids
            ],
            "output_hits": sorted(self.required_output_types & produced_types),
            "missing_input_count": len(plan.get("missing_inputs") or []),
            "step_count": len(skill_ids),
            "has_can_feed_edges": bool(plan.get("can_feed_edges") or []),
            "internal_rank": plan_index,
        }

    def _candidate_skill_pool_for_rerank(
        self,
        recommended_plans: list[dict[str, Any]],
        *,
        seed_skill_ids: tuple[str, ...],
    ) -> list[dict[str, Any]]:
        skill_ids = sorted(_candidate_plan_skill_ids(recommended_plans))
        seed_skill_id_set = set(seed_skill_ids)
        output = []
        for current_skill_id in skill_ids:
            skill = self.skill_by_id.get(current_skill_id)
            if not skill:
                continue
            produced_types = sorted(
                {
                    str(item.get("type") or "").strip().lower()
                    for item in skill.get("outputs") or []
                    if isinstance(item, dict)
                    and str(item.get("type") or "").strip()
                }
            )
            output.append(
                {
                    "skill_id": current_skill_id,
                    "name": str(skill.get("name") or current_skill_id),
                    "description": str(skill.get("description") or "")[:240],
                    "is_retrieval_seed": current_skill_id in seed_skill_id_set,
                    "is_graph_expanded": current_skill_id not in seed_skill_id_set,
                    "produced_artifact_types": produced_types,
                }
            )
        return output

    def _materialize_final_rerank(
        self,
        selection: dict[str, Any],
        *,
        recommended_plans: list[dict[str, Any]],
    ) -> dict[str, Any]:
        selected_index = _positive_int(selection.get("selected_plan_index")) or 1
        if selected_index > len(recommended_plans):
            return {
                "valid": False,
                "detail": f"Final rerank selected invalid plan index: {selected_index}",
            }
        allowed_skill_ids = _candidate_plan_skill_ids(recommended_plans)
        raw_steps = selection.get("steps")
        if raw_steps is None:
            return {
                "valid": True,
                "detail": "",
                "cross_plan_skill_merge": False,
                "plan": {
                    **recommended_plans[selected_index - 1],
                    "reason": _short_text(
                        str(selection.get("reason") or "")
                    )
                    or recommended_plans[selected_index - 1].get("reason", ""),
                    "source": "bidirectional_beam_final_rerank",
                },
            }

        step_ids = _normalize_rerank_step_ids(raw_steps)
        if not step_ids:
            return {"valid": False, "detail": "Final rerank returned no steps."}
        unknown = [
            current_skill_id
            for current_skill_id in step_ids
            if current_skill_id not in allowed_skill_ids
            or current_skill_id not in self.skill_by_id
        ]
        if unknown:
            return {
                "valid": False,
                "detail": f"Final rerank selected unknown skill IDs: {unknown}",
            }

        edge_result = _normalize_rerank_edges(selection.get("can_feed_edges") or [])
        selected_edges = edge_result["edges"]
        if not selected_edges and len(step_ids) > 1:
            selected_edges = [
                (step_ids[index], step_ids[index + 1])
                for index in range(len(step_ids) - 1)
            ]
        step_set = set(step_ids)
        outside = [
            edge
            for edge in selected_edges
            if edge[0] not in step_set or edge[1] not in step_set
        ]
        if outside:
            return {
                "valid": False,
                "detail": f"Final rerank selected edges outside steps: {outside}",
            }
        order = {current_skill_id: index for index, current_skill_id in enumerate(step_ids)}
        backward = [
            edge for edge in selected_edges if order[edge[0]] >= order[edge[1]]
        ]
        if backward:
            return {
                "valid": False,
                "detail": f"Final rerank selected backward edges: {backward}",
            }
        selected_plan_skills = set(
            _dict_plan_signature(recommended_plans[selected_index - 1])
        )
        cross_plan_skill_merge = not set(step_ids) <= selected_plan_skills
        return {
            "valid": True,
            "detail": "",
            "cross_plan_skill_merge": cross_plan_skill_merge,
            "plan": self._final_rerank_plan_payload(
                selection,
                step_ids=step_ids,
                selected_edges=selected_edges,
                edge_reasons=edge_result["reasons"],
                recommended_plans=recommended_plans,
            ),
        }

    def _final_rerank_plan_payload(
        self,
        selection: dict[str, Any],
        *,
        step_ids: list[str],
        selected_edges: list[tuple[str, str]],
        edge_reasons: dict[tuple[str, str], str],
        recommended_plans: list[dict[str, Any]],
    ) -> dict[str, Any]:
        missing_by_skill = _missing_inputs_by_skill(recommended_plans)
        step_reason_by_skill = _step_reasons_by_skill(selection.get("steps") or [])
        steps = []
        produced_artifacts = []
        for index, current_skill_id in enumerate(step_ids, start=1):
            skill = self.skill_by_id[current_skill_id]
            outputs = list(skill.get("outputs") or [])
            produced_artifacts.extend(
                {
                    "name": item.get("name"),
                    "type": item.get("type") or "unknown",
                    "source": "skill_output",
                }
                for item in outputs
                if item.get("name")
            )
            steps.append(
                {
                    "step": index,
                    "skill_id": current_skill_id,
                    "name": str(skill.get("name") or current_skill_id),
                    "inputs": list(skill.get("inputs") or []),
                    "outputs": outputs,
                    "missing_inputs": missing_by_skill.get(current_skill_id, []),
                    "filled_inputs": [],
                    "reason": step_reason_by_skill.get(current_skill_id, ""),
                }
            )
        missing_inputs = [
            item for current in step_ids for item in missing_by_skill.get(current, [])
        ]
        edge_by_key = {
            (skill_id(edge.get("source")), skill_id(edge.get("target"))): edge
            for edge in self.eligible_edges
        }
        edge_items = []
        has_inferred_edges = False
        for edge in selected_edges:
            if edge in edge_by_key:
                edge_items.append(edge_plan_item(edge_by_key[edge]))
                continue
            has_inferred_edges = True
            edge_items.append(
                _beam_final_rerank_inferred_edge_item(
                    edge,
                    edge_reasons.get(edge, ""),
                )
            )
        status = "needs_input" if missing_inputs else "ready"
        reason = _short_text(str(selection.get("reason") or ""))
        return {
            "title": default_beam_plan_title(self.language),
            "status": status,
            "steps": steps,
            "stages": [
                {"stage": index, "skills": [step]}
                for index, step in enumerate(steps, start=1)
            ],
            "produced_artifacts": produced_artifacts,
            "missing_inputs": missing_inputs,
            "can_feed_edges": edge_items,
            "reason": reason,
            "reasons": [reason] if reason else [],
            "plan_classification": (
                "executable"
                if status == "ready"
                else "structurally_valid_but_incomplete"
            ),
            "connectivity_trace": (
                ["can_feed", "beam_final_rerank_inferred"]
                if has_inferred_edges
                else (["can_feed"] if edge_items else [])
            ),
            "source": "bidirectional_beam_final_rerank",
        }

    def _client(self) -> Any:
        if self.llm_client is not None:
            return self.llm_client
        if self.llm_config is None:
            raise ValueError(
                "beam Symphony planning requires llm_config or llm_client."
            )
        return create_llm_client(self.llm_config)

    def _initial_states(self) -> list[BeamState]:
        seeds = self.candidate_skill_ids or self._default_seed_skill_ids()
        states = [
            BeamState(
                skill_ids=(current_skill_id,),
                edge_indices=(),
                available=frozenset(),
                judgement_scores=(1.0,),
                score_reasons=(),
                seed_skill_ids=tuple(seeds),
                directions=frozenset({"seed"}),
            )
            for current_skill_id in seeds
            if current_skill_id in self.skill_by_id
        ]
        return self._rank_and_trim(states, limit=self.effective_top_k)

    def _effective_top_k(self) -> int:
        if self.candidate_skill_ids is None:
            return self.top_k
        return max(self.top_k, len(self.candidate_skill_ids))

    def _reset_subtree_cache(self) -> None:
        self.subtree_cache = {}
        self.subtree_cache_hits = 0
        self.subtree_cache_misses = 0

    def _default_seed_skill_ids(self) -> tuple[str, ...]:
        output: list[str] = []
        seen: set[str] = set()
        for edge in self.eligible_edges:
            for key in ("source", "target"):
                current_skill_id = skill_id(edge.get(key))
                if (
                    current_skill_id
                    and current_skill_id in self.skill_by_id
                    and current_skill_id not in seen
                ):
                    seen.add(current_skill_id)
                    output.append(current_skill_id)
                if len(output) >= BEAM_DEFAULT_MAX_SKILLS:
                    return tuple(output)
        if output:
            return tuple(output)
        for skill in self.artifacts.skills[:BEAM_DEFAULT_MAX_SKILLS]:
            current_skill_id = str(skill.get("id") or "").strip()
            if current_skill_id:
                output.append(current_skill_id)
        return tuple(output)

    def _expansion_groups(
        self,
        query_signature: str,
        states: list[BeamState],
    ) -> tuple[
        list[list[NeighborExpansion]],
        dict[str, PlannerJudgement],
        list[BeamState],
    ]:
        groups: list[list[NeighborExpansion]] = []
        cached: dict[str, PlannerJudgement] = {}
        subtree_states: list[BeamState] = []
        current_expansions: dict[str, NeighborExpansion] = {}
        pending_keys: dict[tuple[str, str, str], str] = {}
        aliases: dict[str, list[str]] = defaultdict(list)
        for state in states:
            for direction, current_skill_id in (
                ("forward", state.tail),
                ("backward", state.head),
            ):
                expansions = self._neighbor_expansions(
                    state=state,
                    direction=direction,
                    current_skill_id=current_skill_id,
                )
                subtree_key = (query_signature, direction, current_skill_id)
                if subtree_key in self.subtree_cache:
                    self.subtree_cache_hits += 1
                    subtree_states.extend(
                        self._states_from_subtree_cache(
                            state=state,
                            direction=direction,
                            entries=self.subtree_cache[subtree_key],
                        )
                    )
                    continue
                misses = []
                for expansion in expansions:
                    current_expansions[expansion.candidate_id] = expansion
                    judgement = self.cache.get(query_signature, expansion)
                    if judgement is None:
                        misses.append(expansion)
                    else:
                        cached[expansion.candidate_id] = judgement
                if misses:
                    self.subtree_cache_misses += 1
                    deduped_misses = []
                    for expansion in misses:
                        key = self.cache.key_for(query_signature, expansion)
                        existing_candidate_id = pending_keys.get(key)
                        if existing_candidate_id is not None:
                            aliases[existing_candidate_id].append(
                                expansion.candidate_id
                            )
                            continue
                        pending_keys[key] = expansion.candidate_id
                        deduped_misses.append(expansion)
                    if deduped_misses:
                        groups.append(deduped_misses)
        self._current_expansions = current_expansions
        self._current_expansion_aliases = aliases
        return groups, cached, subtree_states

    def _states_from_subtree_cache(
        self,
        *,
        state: BeamState,
        direction: str,
        entries: tuple[SubtreeCacheEntry, ...],
    ) -> list[BeamState]:
        output = []
        for entry in entries:
            if entry.candidate_skill_id in state.skill_ids:
                continue
            if direction == "forward":
                skill_ids = (*state.skill_ids, entry.candidate_skill_id)
                edge_indices = (*state.edge_indices, entry.edge_index)
            else:
                skill_ids = (entry.candidate_skill_id, *state.skill_ids)
                edge_indices = (entry.edge_index, *state.edge_indices)
            output.append(
                BeamState(
                    skill_ids=skill_ids,
                    edge_indices=edge_indices,
                    available=state.available,
                    judgement_scores=(
                        *state.judgement_scores,
                        entry.judgement_score,
                    ),
                    score_reasons=_append_unique(
                        state.score_reasons,
                        entry.reason,
                    ),
                    seed_skill_ids=state.seed_skill_ids,
                    directions=state.directions | {direction},
                )
            )
        return output

    def _record_subtree_judgements(
        self,
        query_signature: str,
        judgements: dict[str, PlannerJudgement],
    ) -> None:
        entries_by_key: dict[
            tuple[str, str, str],
            dict[tuple[str, int], SubtreeCacheEntry],
        ] = defaultdict(dict)
        for candidate_id, judgement in judgements.items():
            if judgement.score < JUDGEMENT_SCORE_THRESHOLD:
                continue
            expansion = self._expansion_by_id(candidate_id)
            if expansion is None:
                continue
            key = (
                query_signature,
                expansion.direction,
                expansion.current_skill_id,
            )
            entries_by_key[key][
                (expansion.candidate_skill_id, expansion.edge_index)
            ] = SubtreeCacheEntry(
                candidate_skill_id=expansion.candidate_skill_id,
                edge_index=expansion.edge_index,
                judgement_score=judgement.score,
                reason=judgement.reason,
            )
        for key, entries in entries_by_key.items():
            if key in self.subtree_cache:
                continue
            self.subtree_cache[key] = tuple(entries.values())

    def _apply_judgement_aliases(
        self,
        judgements: dict[str, PlannerJudgement],
    ) -> dict[str, PlannerJudgement]:
        output = dict(judgements)
        for source_id, alias_ids in getattr(
            self,
            "_current_expansion_aliases",
            {},
        ).items():
            judgement = judgements.get(source_id)
            if judgement is None:
                continue
            for alias_id in alias_ids:
                output[alias_id] = PlannerJudgement(
                    candidate_id=alias_id,
                    score=judgement.score,
                    reason=judgement.reason,
                )
        return output

    def _neighbor_expansions(
        self,
        *,
        state: BeamState,
        direction: str,
        current_skill_id: str,
    ) -> list[NeighborExpansion]:
        if state.depth >= self.max_depth:
            return []
        edge_indices = (
            self.outgoing_edges.get(current_skill_id, [])
            if direction == "forward"
            else self.incoming_edges.get(current_skill_id, [])
        )
        expansions = []
        for edge_index in edge_indices:
            edge = self.eligible_edges[edge_index]
            candidate_skill_id = (
                skill_id(edge.get("target"))
                if direction == "forward"
                else skill_id(edge.get("source"))
            )
            if (
                not candidate_skill_id
                or candidate_skill_id not in self.skill_by_id
                or candidate_skill_id in state.skill_ids
            ):
                continue
            expansions.append(
                NeighborExpansion(
                    candidate_id=(
                        f"{direction}:{edge_index}:"
                        f"{_state_signature(state)}:{candidate_skill_id}"
                    ),
                    state=state,
                    direction=direction,
                    current_skill_id=current_skill_id,
                    candidate_skill_id=candidate_skill_id,
                    edge_index=edge_index,
                )
            )
        return expansions

    def _apply_judgements(
        self,
        judgements: dict[str, PlannerJudgement],
    ) -> list[BeamState]:
        output = []
        for candidate_id, judgement in judgements.items():
            if judgement.score < JUDGEMENT_SCORE_THRESHOLD:
                continue
            expansion = self._expansion_by_id(candidate_id)
            if expansion is None:
                continue
            state = expansion.state
            if expansion.direction == "forward":
                skill_ids = (*state.skill_ids, expansion.candidate_skill_id)
                edge_indices = (*state.edge_indices, expansion.edge_index)
            else:
                skill_ids = (expansion.candidate_skill_id, *state.skill_ids)
                edge_indices = (expansion.edge_index, *state.edge_indices)
            output.append(
                BeamState(
                    skill_ids=skill_ids,
                    edge_indices=edge_indices,
                    available=state.available,
                    judgement_scores=(*state.judgement_scores, judgement.score),
                    score_reasons=_append_unique(
                        state.score_reasons,
                        judgement.reason,
                    ),
                    seed_skill_ids=state.seed_skill_ids,
                    directions=state.directions | {expansion.direction},
                )
            )
        return output

    def _expansion_by_id(self, candidate_id: str) -> NeighborExpansion | None:
        return getattr(self, "_current_expansions", {}).get(candidate_id)

    def _reset_beam_progress(self) -> None:
        self._beam_event_sequence = 0
        self._beam_events = []
        self._beam_graph = BeamSearchGraph(self.skill_by_id, self.eligible_edges)

    async def _emit_beam_event(
        self,
        event: str,
        *,
        round_index: int,
        payload: dict[str, Any],
    ) -> None:
        self._beam_event_sequence += 1
        item = {
            "type": f"symphony.beam_search.{event}",
            "event": event,
            "language": self.language,
            "sequence": self._beam_event_sequence,
            "round": round_index,
            "payload": payload,
        }
        self._beam_events.append(_json_safe(item))
        if self.progress_callback is None:
            return
        try:
            result = self.progress_callback(_json_safe(item))
            if asyncio.iscoroutine(result):
                await result
        except Exception as exc:
            logger.debug("beam progress callback failed: %s", exc)

    def _record_candidates_found(self) -> list[dict[str, Any]]:
        output = []
        for expansion in _sorted_expansions(
            getattr(self, "_current_expansions", {}).values()
        ):
            output.append(self._beam_graph.add_candidate(expansion))
        return output

    def _record_candidates_judged(
        self,
        judgements: dict[str, PlannerJudgement],
    ) -> list[dict[str, Any]]:
        output = []
        for candidate_id in sorted(judgements):
            expansion = self._expansion_by_id(candidate_id)
            if expansion is None:
                continue
            output.append(
                self._beam_graph.apply_judgement(
                    expansion,
                    judgements[candidate_id],
                )
            )
        return output

    def _round_summary(
        self,
        *,
        round_index: int,
        frontier: list[BeamState],
        groups: list[list[NeighborExpansion]],
        cached: dict[str, PlannerJudgement],
        judgements: dict[str, PlannerJudgement],
        retained: list[BeamState],
    ) -> dict[str, Any]:
        candidates = []
        for candidate_id, judgement in judgements.items():
            expansion = self._expansion_by_id(candidate_id)
            if expansion is None:
                continue
            candidates.append(
                self._candidate_status_summary(expansion, judgement)
            )
        candidates.sort(
            key=lambda item: (
                item["status"] != "selected",
                item["direction"],
                item["candidate_skill_id"],
            )
        )
        retained_summaries = [
            self._state_summary(state, rank=index)
            for index, state in enumerate(retained, start=1)
        ]
        return {
            "round": round_index,
            "frontier_count": len(frontier),
            "judge_request_count": len(groups),
            "fresh_candidate_count": sum(len(group) for group in groups),
            "cached_candidate_count": len(cached),
            "judged_candidate_count": len(candidates),
            "candidate_count": len(candidates),
            "selected_count": sum(
                1 for item in candidates if item["status"] == "selected"
            ),
            "rejected_count": sum(
                1 for item in candidates if item["status"] == "rejected"
            ),
            "accepted_count": sum(
                1 for item in candidates if item["status"] == "selected"
            ),
            "retained_count": len(retained_summaries),
            "candidates": candidates,
            "retained_paths": retained_summaries,
        }

    def _candidate_status_summary(
        self,
        expansion: NeighborExpansion,
        judgement: PlannerJudgement,
    ) -> dict[str, Any]:
        edge = self.eligible_edges[expansion.edge_index]
        status = (
            "selected"
            if judgement.score >= JUDGEMENT_SCORE_THRESHOLD
            else "rejected"
        )
        return {
            "candidate_id": expansion.candidate_id,
            "direction": expansion.direction,
            "current_skill_id": expansion.current_skill_id,
            "candidate_skill_id": expansion.candidate_skill_id,
            "candidate_label": _skill_label(
                self.skill_by_id.get(expansion.candidate_skill_id, {})
            ),
            "status": status,
            "edge": {
                "id": f"{expansion.current_skill_id}->{expansion.candidate_skill_id}",
                "source": expansion.current_skill_id,
                "target": expansion.candidate_skill_id,
                "confidence": edge.get("confidence"),
            },
            "path": list(expansion.state.skill_ids),
        }

    def _state_summary(self, state: BeamState, *, rank: int) -> dict[str, Any]:
        return {
            "rank": rank,
            "score": round(self._state_score(state), 4),
            "skill_ids": list(state.skill_ids),
            "edge_count": len(state.edge_indices),
            "directions": sorted(state.directions),
        }

    def _final_candidate_states(
        self,
        *,
        searched_states: list[BeamState],
        seed_states: list[BeamState],
    ) -> list[BeamState]:
        ranked_search = self._rank_and_trim(
            searched_states,
            limit=self._final_candidate_limit(),
        )
        return self._dedupe_states([*ranked_search, *seed_states])

    def _final_candidate_limit(self) -> int:
        return max(self.effective_top_k * 3, self.effective_top_k + 8)

    def _plans_from_states(self, states: list[BeamState]) -> list[OrchestrationPlan]:
        state_plans = [
            (
                state,
                state_to_plan(
                    state=state.to_search_state(),
                    grounded=GroundedQuery(
                        query="",
                        available_artifacts=[],
                        seed_skill_ids=state.seed_skill_ids,
                    ),
                    skill_by_id=self.skill_by_id,
                    can_feed_edges=self.eligible_edges,
                ),
            )
            for state in states
            if state.skill_ids
        ]
        state_plans.sort(
            key=lambda item: (
                -self._state_score(item[0]),
                len(item[1].missing_inputs),
                len(item[1].steps),
                tuple(step.skill_id for step in item[1].steps),
            )
        )
        return [
            plan
            for _state, plan in self._seed_preserving_state_plans(state_plans)
        ]

    def _seed_preserving_state_plans(
        self,
        state_plans: list[tuple[BeamState, OrchestrationPlan]],
    ) -> list[tuple[BeamState, OrchestrationPlan]]:
        if not state_plans:
            return []
        seed_skill_ids = tuple(
            dict.fromkeys(
                seed_id
                for state, _plan in state_plans
                for seed_id in state.seed_skill_ids
            )
        )
        if not seed_skill_ids:
            return state_plans

        selected = [state_plans[0]]
        selected_signatures = {_plan_signature(state_plans[0][1])}
        covered_seeds = _plan_skill_ids(state_plans[0][1]) & set(seed_skill_ids)
        for seed_id in seed_skill_ids:
            if seed_id in covered_seeds:
                continue
            match = next(
                (
                    item
                    for item in state_plans
                    if seed_id in _plan_skill_ids(item[1])
                    and _plan_signature(item[1]) not in selected_signatures
                ),
                None,
            )
            if match is None:
                continue
            selected.append(match)
            selected_signatures.add(_plan_signature(match[1]))
            covered_seeds |= _plan_skill_ids(match[1]) & set(seed_skill_ids)

        for item in state_plans:
            signature = _plan_signature(item[1])
            if signature in selected_signatures:
                continue
            selected.append(item)
            selected_signatures.add(signature)
        return selected

    def _merge_states(self, states: list[BeamState]) -> list[BeamState]:
        deduped = self._dedupe_states(states)
        merged = list(deduped)
        for groups in (
            _group_states(deduped, lambda state: state.tail),
            _group_states(deduped, lambda state: state.head),
            _group_states(
                deduped,
                lambda state: ",".join(sorted(state.skill_ids)),
            ),
        ):
            for group in groups:
                if len(group) < 2:
                    continue
                merged_state = self._merge_state_group(group)
                if merged_state is not None:
                    merged.append(merged_state)
        return self._dedupe_states(merged)

    def _merge_state_group(self, states: list[BeamState]) -> BeamState | None:
        skill_ids = {current for state in states for current in state.skill_ids}
        edge_indices = tuple(
            sorted(
                {
                    edge_index
                    for state in states
                    for edge_index in state.edge_indices
                }
            )
        )
        ordered = self._topological_order(skill_ids, edge_indices)
        if ordered is None:
            return None
        seed_skill_ids = tuple(
            dict.fromkeys(
                current
                for state in states
                for current in state.seed_skill_ids
            )
        )
        judgement_scores = tuple(
            score for state in states for score in state.judgement_scores
        )
        reasons = tuple(
            dict.fromkeys(
                reason
                for state in states
                for reason in state.score_reasons
                if reason
            )
        )
        directions = frozenset(
            direction
            for state in states
            for direction in state.directions
        )
        return BeamState(
            skill_ids=tuple(ordered),
            edge_indices=edge_indices,
            available=frozenset(),
            judgement_scores=judgement_scores or (1.0,),
            score_reasons=reasons[:8],
            seed_skill_ids=seed_skill_ids,
            directions=directions,
        )

    def _topological_order(
        self,
        skill_ids: set[str],
        edge_indices: tuple[int, ...],
    ) -> list[str] | None:
        incoming = {current_skill_id: 0 for current_skill_id in skill_ids}
        outgoing: dict[str, list[str]] = defaultdict(list)
        for edge_index in edge_indices:
            edge = self.eligible_edges[edge_index]
            source_id = skill_id(edge.get("source"))
            target_id = skill_id(edge.get("target"))
            if source_id not in skill_ids or target_id not in skill_ids:
                continue
            outgoing[source_id].append(target_id)
            incoming[target_id] += 1

        ready = sorted(
            current_skill_id
            for current_skill_id, count in incoming.items()
            if count == 0
        )
        ordered = []
        while ready:
            current_skill_id = ready.pop(0)
            ordered.append(current_skill_id)
            for target_id in sorted(outgoing.get(current_skill_id, [])):
                incoming[target_id] -= 1
                if incoming[target_id] == 0:
                    ready.append(target_id)
                    ready.sort()
        if len(ordered) != len(skill_ids):
            return None
        return ordered

    def _dedupe_states(self, states: list[BeamState]) -> list[BeamState]:
        deduped: dict[tuple[tuple[str, ...], tuple[int, ...]], BeamState] = {}
        for state in states:
            key = (state.skill_ids, tuple(sorted(state.edge_indices)))
            existing = deduped.get(key)
            if (
                existing is None
                or self._state_score(state) > self._state_score(existing)
            ):
                deduped[key] = state
        return list(deduped.values())

    def _rank_and_trim(
        self,
        states: list[BeamState],
        *,
        limit: int,
    ) -> list[BeamState]:
        return sorted(
            self._dedupe_states(states),
            key=lambda state: (
                -self._state_score(state),
                self._state_missing_count(state),
                len(state.skill_ids),
                state.skill_ids,
            ),
        )[:limit]

    def _state_score(self, state: BeamState) -> float:
        plan = self._state_plan(state)
        judgement_score = (
            sum(state.judgement_scores) / len(state.judgement_scores)
            if state.judgement_scores
            else 0.0
        )
        edge_confidence = self._state_edge_confidence(state)
        input_coverage = self._input_coverage(plan)
        seed_coverage = self._state_seed_coverage(state)
        output_coverage = self._state_output_coverage(state)
        depth_penalty = max(0, len(state.skill_ids) - 1)
        return (
            0.30 * judgement_score
            + 0.20 * edge_confidence
            + 0.15 * input_coverage
            + 0.20 * seed_coverage
            + 0.35 * output_coverage
            - 0.03 * depth_penalty
        )

    @staticmethod
    def _state_seed_coverage(state: BeamState) -> float:
        seed_skill_ids = set(state.seed_skill_ids)
        if not seed_skill_ids:
            return 0.0
        return len(set(state.skill_ids) & seed_skill_ids) / len(seed_skill_ids)

    def _state_output_coverage(self, state: BeamState) -> float:
        required_output_types = self.required_output_types
        if not required_output_types:
            return 0.0
        plan = self._state_plan(state)
        produced_types = {
            str(artifact.type or "").strip().lower()
            for artifact in plan.produced_artifacts
        }
        covered = required_output_types & produced_types
        return len(covered) / len(required_output_types)

    def _state_plan(self, state: BeamState) -> OrchestrationPlan:
        return state_to_plan(
            state=state.to_search_state(),
            grounded=GroundedQuery(
                query="",
                available_artifacts=[],
                seed_skill_ids=state.seed_skill_ids,
            ),
            skill_by_id=self.skill_by_id,
            can_feed_edges=self.eligible_edges,
        )

    def _state_missing_count(self, state: BeamState) -> int:
        return len(self._state_plan(state).missing_inputs)

    def _state_edge_confidence(self, state: BeamState) -> float:
        if not state.edge_indices:
            return 1.0
        values = [
            float(self.eligible_edges[index].get("confidence") or 0.0)
            for index in state.edge_indices
        ]
        return sum(values) / len(values)

    @staticmethod
    def _input_coverage(plan: OrchestrationPlan) -> float:
        required = 0
        for step in plan.steps:
            required += sum(
                1 for item in step.inputs if item.get("required", True)
            )
        if required <= 0:
            return 1.0
        missing = len(plan.missing_inputs)
        return max(0.0, min(1.0, (required - missing) / required))

    def _candidate_payload(self, expansion: NeighborExpansion) -> dict[str, Any]:
        return {
            "candidate_id": expansion.candidate_id,
            "skill": self._skill_payload(
                self.skill_by_id[expansion.candidate_skill_id]
            ),
        }

    @staticmethod
    def _skill_payload(skill: dict[str, Any]) -> dict[str, Any]:
        current_skill_id = str(skill.get("id") or "")
        return {
            "id": current_skill_id,
            "name": str(skill.get("name") or current_skill_id),
            "description": str(skill.get("description") or "")[:800],
        }

    def _sorted_eligible_edges(self) -> list[dict[str, Any]]:
        filtered_edges = []
        for edge in self.artifacts.graph.get("edges", []):
            edge_confidence = float(edge.get("confidence") or 0.0)
            source_id = skill_id(edge.get("source"))
            target_id = skill_id(edge.get("target"))
            if (
                edge.get("type") == "can_feed"
                and edge_confidence >= self.min_edge_confidence
                and source_id in self.skill_by_id
                and target_id in self.skill_by_id
            ):
                filtered_edges.append(edge)
        return sorted(
            filtered_edges,
            key=lambda item: (
                -float(item.get("confidence") or 0.0),
                skill_id(item.get("source")),
                skill_id(item.get("target")),
            ),
        )

    def _plan_payload(self, plan: OrchestrationPlan, *, query: str) -> dict[str, Any]:
        payload = plan.to_dict()
        title = _query_plan_title(query, language=self.language)
        reason = "; ".join(plan.reasons[:3])
        payload.update(
            {
                "title": title,
                "reason": reason,
                "plan_classification": (
                    "executable"
                    if plan.status == "ready"
                    else "structurally_valid_but_incomplete"
                ),
                "connectivity_trace": (
                    ["can_feed"] if plan.can_feed_edges else []
                ),
                "source": "bidirectional_beam",
            }
        )
        return payload

    @staticmethod
    def _normalize_candidate_skill_ids(
        values: Sequence[str] | None,
        *,
        known_skill_ids: set[str],
    ) -> tuple[str, ...] | None:
        if values is None:
            return None
        output = []
        seen = set()
        for value in values:
            current_skill_id = str(value or "").strip()
            if (
                not current_skill_id
                or current_skill_id in seen
                or current_skill_id not in known_skill_ids
            ):
                continue
            seen.add(current_skill_id)
            output.append(current_skill_id)
        return tuple(output) if output else None


def _query_signature(query: str) -> str:
    normalized = " ".join(str(query or "").strip().lower().split())
    return hashlib.sha1(normalized.encode("utf-8")).hexdigest()


def _state_signature(state: BeamState) -> str:
    payload = {
        "skills": state.skill_ids,
        "edges": state.edge_indices,
        "directions": sorted(state.directions),
    }
    return hashlib.sha1(
        json.dumps(payload, sort_keys=True, default=str).encode("utf-8")
    ).hexdigest()[:10]


def _plan_skill_ids(plan: OrchestrationPlan) -> set[str]:
    return {step.skill_id for step in plan.steps if step.skill_id}


def _plan_signature(plan: OrchestrationPlan) -> tuple[str, ...]:
    return tuple(step.skill_id for step in plan.steps if step.skill_id)


def _dict_plan_signature(plan: dict[str, Any]) -> tuple[str, ...]:
    return tuple(
        str(step.get("skill_id") or "").strip()
        for step in plan.get("steps") or []
        if isinstance(step, dict) and str(step.get("skill_id") or "").strip()
    )


def _candidate_plan_skill_ids(plans: list[dict[str, Any]]) -> set[str]:
    return {
        current_skill_id
        for plan in plans
        for current_skill_id in _dict_plan_signature(plan)
    }


def _normalize_rerank_step_ids(raw_steps: Any) -> list[str]:
    if not isinstance(raw_steps, list):
        return []
    output = []
    for item in raw_steps:
        current_skill_id = skill_id(
            item.get("skill_id") if isinstance(item, dict) else item
        ).strip()
        if current_skill_id and current_skill_id not in output:
            output.append(current_skill_id)
    return output


def _normalize_rerank_edges(raw_edges: Any) -> dict[str, Any]:
    edges: list[tuple[str, str]] = []
    reasons: dict[tuple[str, str], str] = {}
    if not isinstance(raw_edges, list):
        return {"edges": edges, "reasons": reasons}
    seen: set[tuple[str, str]] = set()
    for item in raw_edges:
        if not isinstance(item, dict):
            continue
        source_id = skill_id(item.get("source_id") or item.get("source")).strip()
        target_id = skill_id(item.get("target_id") or item.get("target")).strip()
        if not source_id or not target_id or source_id == target_id:
            continue
        edge = (source_id, target_id)
        if edge in seen:
            continue
        seen.add(edge)
        edges.append(edge)
        reasons[edge] = _short_text(str(item.get("reason") or ""))
    return {"edges": edges, "reasons": reasons}


def _positive_int(value: Any) -> int | None:
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        return None
    return parsed if parsed > 0 else None


def _short_text(value: str, *, max_chars: int = 80) -> str:
    text = " ".join(str(value or "").split())
    if len(text) <= max_chars:
        return text
    return text[:max_chars].rstrip()


def _missing_inputs_by_skill(
    plans: list[dict[str, Any]],
) -> dict[str, list[dict[str, Any]]]:
    output: dict[str, list[dict[str, Any]]] = {}
    for plan in plans:
        for item in plan.get("missing_inputs") or []:
            if not isinstance(item, dict):
                continue
            current_skill_id = str(item.get("skill_id") or "").strip()
            if current_skill_id:
                output.setdefault(current_skill_id, []).append(item)
        for step in plan.get("steps") or []:
            if not isinstance(step, dict):
                continue
            current_skill_id = str(step.get("skill_id") or "").strip()
            if not current_skill_id:
                continue
            for item in step.get("missing_inputs") or []:
                if isinstance(item, dict):
                    output.setdefault(current_skill_id, []).append(item)
    return output


def _step_reasons_by_skill(raw_steps: Any) -> dict[str, str]:
    if not isinstance(raw_steps, list):
        return {}
    output = {}
    for item in raw_steps:
        if not isinstance(item, dict):
            continue
        current_skill_id = skill_id(item.get("skill_id")).strip()
        if current_skill_id:
            output[current_skill_id] = _short_text(str(item.get("reason") or ""))
    return output


def _beam_final_rerank_inferred_edge_item(
    edge: tuple[str, str],
    reason: str,
) -> dict[str, Any]:
    return {
        "source_id": edge[0],
        "target_id": edge[1],
        "confidence": None,
        "method": "beam_final_rerank_inferred",
        "port_mappings": [],
        "source_outputs": [],
        "target_inputs": [],
        "reasons": [reason] if reason else [],
        "reason": reason,
    }


def _clamp_score(value: Any) -> float:
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return 0.0
    return max(0.0, min(1.0, parsed))


def _query_plan_title(query: str, *, language: str) -> str:
    title = " ".join(str(query or "").split())
    if not title:
        return default_beam_plan_title(language)
    if len(title) <= 80:
        return title
    return f"{title[:77].rstrip()}..."


def _append_unique(values: tuple[str, ...], value: str) -> tuple[str, ...]:
    text = str(value or "").strip()
    if not text or text in values:
        return values
    return (*values, text)


def _group_states(
    states: list[BeamState],
    key_fn: Callable[[BeamState], str],
) -> list[list[BeamState]]:
    grouped: dict[str, list[BeamState]] = defaultdict(list)
    for state in states:
        grouped[str(key_fn(state))].append(state)
    return list(grouped.values())


def _dominant_status(current: str, incoming: str) -> str:
    current_priority = _GRAPH_STATUS_PRIORITY.get(current, -1)
    incoming_priority = _GRAPH_STATUS_PRIORITY.get(incoming, -1)
    return incoming if incoming_priority >= current_priority else current


def _direction_label(directions: list[str]) -> str:
    filtered = [item for item in directions if item and item != "final"]
    if not filtered:
        return ""
    if len(filtered) == 1:
        return filtered[0]
    if "seed" in filtered and len(filtered) == 2:
        return next(item for item in filtered if item != "seed")
    return "mixed"


def _copy_public_graph_edge(edge: dict[str, Any]) -> dict[str, Any]:
    output = {
        "id": edge.get("id"),
        "source": edge.get("source"),
        "target": edge.get("target"),
        "status": edge.get("status"),
        "confidence": edge.get("confidence"),
    }
    direction = edge.get("direction")
    if direction not in (None, ""):
        output["direction"] = direction
    return output


def _max_confidence(left: Any, right: Any) -> Any:
    try:
        left_value = float(left)
    except (TypeError, ValueError):
        return right
    try:
        right_value = float(right)
    except (TypeError, ValueError):
        return left
    return max(left_value, right_value)


def _skill_label(skill: dict[str, Any]) -> str:
    current_skill_id = str(skill.get("id") or "").strip()
    return str(skill.get("name") or current_skill_id).strip() or current_skill_id


def _json_safe(payload: dict[str, Any]) -> dict[str, Any]:
    return json.loads(json.dumps(payload, ensure_ascii=False, default=str))


def _required_output_types_from_query(query: str) -> frozenset[str]:
    output_types = set()
    for match in _EXPLICIT_FILE_EXTENSION_RE.finditer(str(query or "")):
        output_type = _output_type_from_extension(match.group(1))
        if output_type:
            output_types.add(output_type)
    return frozenset(output_types)


def _output_type_from_extension(extension: str) -> str | None:
    normalized = str(extension or "").strip().lower().lstrip(".")
    if not normalized:
        return None
    mime_type, _encoding = mimetypes.guess_type(f"file.{normalized}")
    if mime_type in _MIME_TO_OUTPUT_TYPE:
        return _MIME_TO_OUTPUT_TYPE[mime_type]
    if mime_type and mime_type.startswith("image/"):
        return "image"
    return None


def _sorted_expansions(
    expansions: Sequence[NeighborExpansion],
) -> list[NeighborExpansion]:
    return sorted(
        expansions,
        key=lambda item: (
            item.direction,
            item.current_skill_id,
            item.candidate_skill_id,
            item.edge_index,
            item.candidate_id,
        ),
    )
